#!/bin/bash 

#update template
cd ~/tools/pikpik/ && git pull && cd - 2&> /dev/null
nuclei -update-templates 2&> /dev/null
cd ~/global


#scan prog
for  prog in $(find  ./ -maxdepth 1 -type d |rev |cut -d "/" -f 1|rev);do
	cd $prog
	~/my_scripts/ncl_split2 Hosts update_nuclei ~/tools/pikpik/nuclei/ high,critical,medium,low | notify	
	~/my_scripts/ncl_split2 Hosts update_nuclei ~/nuclei-templates/ high,critical,medium,low | notify
	cd ..
done

