#!/bin/bash 

file=$1
host=$2
function test_it(){
    normal=$(curl -s -o /dev/null -w "%{http_code} %{size_download}"   $i)
    modified=$(curl -s -o /dev/null -w "%{http_code} %{size_download}"  -H "Host: $host" $i)
    echo  "$i [$normal]  [$modified]" |tee host_header_test.out
}

for i in $(cat $file);do
    normal=$(curl -s -o /dev/null -w "%{http_code} %{size_download}"   $i)
    modified=$(curl -s -o /dev/null -w "%{http_code} %{size_download}"  -H "Host: $host" $i)
    echo -e " $i \033[0;31m[$normal]  \033[0;32m[$modified]\033[0m" |tee host_header_test.out
done