#!/bin/bash 


function a(){
	filename=$(echo "$1" | sha256sum |awk '{print $1}')
	echo $1 | kxss |tee -a ./x/$filename
	find ./x -name $filename -empty -delete
}

mkdir -p x 
export -f a
cat $1 | xargs -n 1 -P 100 -I {} bash -c 'a "$@"' _ {}
cat ./x/* > ./$1_xss  &&  rm -rf ./x/
