#!/bin/bash


# url file to scan 
#split taille
#nuclei template
$sevirity

# test if there is already scan done before in this repo 
# to create a inore file  for this repos 
echo "step1"
if [[ -f ./.templates ]]; then 
	cat $3/.nuclei-ignore > $3/.nuclei-ignore2
	cat ./.templates > $3/.nuclei-ignore
fi

echo "step2"

# create  split for  scan file if  doesn t exist
if [[ ! $(find ./ -iname "host_*") ]]; then
	split -l $2 $1  host_
fi

echo "step3"
#lanch the scan 
for file in $(ls host_* );do
	nuclei -l $file  -t $3   -stats -timeout 5  -severity $4 | tee -a nuclei_split
	rm -rf $file
done

echo "step4"

#get the templates that is used 
cd $3 && find ./ -iname "*.yaml" | find ./ -iname "*.yaml" |grep -r  "$4" |cut -d ":" -f 1   >>  ./.templates && cd -
mv $3/.templates .
cat .templates |sort -uo .templates

echo "step5"
#return the default ingnore file 
if [[ -f $3/.nuclei-ignore2 ]]; then
        cat $3/.nuclei-ignore2 > $3/.nuclei-ignore
fi




