#!/bin/bash 





path="parameters_dir"
scope=../scope
hosts=../Hosts
fuzz_list=../$1
colab=$2

#get urls
function get_urls(){
	for url in $(cat $scope );do
		echo $url |waybackurls |tee -a urls.txt
		echo $url |gau  |tee -a urls.txt
	done	
}

function spider(){
	gospider -S $hosts -o output -c 100 -d 1 --other-source --include-subs 
	cat ./output/* /* |grep  -oiEh "https?://[^\"\\'> ]+" |sort -u |tee -a urls.txt 
	rm -rf ./output
}

#classification
function classify(){
	cat urls.txt |unfurl -u keys |sort -u |tee -a parameters.txt
	cat urls.txt | unfurl format ?%q |sort -u |tee -a multiple_param.txt
}

#fuzz 
function create_param_string(){
	cat multiple_param.txt  | qsreplace "$colab"|sort -uo multiple_param.txt
	# try do  create a function to send one parameter value each time 
}

function fuzz(){
	ffuf -w parameters.txt:PARAM -w $fuzz_list:URL -u "URL?PARAM=$colab" 
	ffuf -w multiple_param.txt:PARAM -w $fuzz_list:URL -u URLPARAM 

function verify_tools(){
	#wayback
	if ! command -v "waybackurls" &> /dev/null
	then
    	tool="waybackurls"
		echo "you shood install all the tools , $tool is missing !!!"
		echo "this script neen the following toolsto work : ffuf,gau,gospider,waybackurls,qsreplace"
		exit ;
	fi
	#gau
	if ! command -v "gau" &> /dev/null
	then
		tool="gau"
		echo "you shood install all the tools ,$tool is missing !!!"
		echo "this script neen the following toolsto work : ffuf,gau,gospider,waybackurls,qsreplace"
		exit ;
	fi
	#gospider
	if ! command -v "gospider" &> /dev/null
	then
    	tool="gospider"
		echo "you shood install all the tools ,$tool is missing !!!"
		echo "this script neen the following toolsto work : ffuf,gau,gospider,waybackurls,qsreplace"
		exit ;
	fi
	#ffuf
	if ! command -v "ffuf" &> /dev/null
	then
    	tool="ffuf"
		echo "you shood install all the tools ,$tool is missing !!!"
		echo "this script neen the following toolsto work : ffuf,gau,gospider,waybackurls,qsreplace"
		exit ;
	fi
	#qsreplace
	if ! command -v "qsreplace" &> /dev/null
	then
    	tool="qsreplace"
		echo "you shood install all the tools ,$tool is missing !!!"
		echo " this script neen the following toolsto work : ffuf,gau,gospider,waybackurls,qsreplace"
		exit ;
	fi

}

function main(){
	mkdir -p $path && cd $path
	# echo " $path $scope   $hosts    $fuzz_list"
	echo "get urls"
	get_urls
	# spider
	# echo "$cola"
	echo "classify"
	classify
	echo "create parameter"
	create_param_string
	fuzz
}


if [[ ! $# == 2 ]];then
	echo "you shoud enter host file to fuzz and colab server !!!!"
	exit ;
else
	verify_tools
	# main
	echo "no problem"
fi

