#!/bin/bash 


while true; do
	cd ~/tools/pikpik && git pull && cd - 2&> /dev/null
	nuclei -update-templates	
	cd ~/global
	for prog in $(find ./ -maxdepth 1 -type d | grep -wv "./");do
		cd $prog
		echo  $prog
		subfinder -dL scope -all | anew Domains | httpx -silent  | nuclei -silent -t ~/tools/pikpik/nuclei -t ~/nuclei-templates -severity critical,high,medium,low   -timeout 5 -c 400  |anew  out_nucl| notify  -silent
		cd - 
	done
	sleep 7200
done

