#!/bin/bash

host=$1
resolvers=~/wordlists/resolvers.txt
wordlist=~/wordlists/sub.txt

echo $host $resolvers $wordlist

for i in $( seq 2 6);do
	cat $host |grep -Po "(\.[\w-]+){$i}$"|sort -u  |sed "s/^.//g" |tee -a  deeplevels.txt
done

cat  deeplevels.txt |sort -uo deeplevels.txt

#bruteforce
for hs in $(cat  deeplevels.txt);do
	awk -v h=$hs '{print $0"."h}' $wordlist  >> list.txt
	echo "massdns worke with $hs"
	massdns list.txt -r $resolvers -t A -o S -w deepdomain.txt -q 
	echo "massdns end with $hs"
	cat deepdomain.txt |awk -F ". " "{print $1}" |sort -u |httpx -silent  -threads 100 |tee -a deeplevels_rslv.txt
	rm list.txt deepdomain.txt
done 

# gett only unique subds
# cat $host |sort -uo $host
# cat deeplevels_rslv.txt |sort -uo deeplevels_rslv.txt
# comm -13 $host deeplevels_rslv.txt |sort -uo deeplevels_rslv.txt

